use_frameworks!

platform :ios, '8.0'

target 'DNNetworking_Example' do
  pod 'DNNetworking', :path => '../'

  target 'DNNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
